### ISSUE TITLE
Small cosmetic issue when changing $nav-width

### ISSUE THREAD

**Issue by TimoteusRuotsalainen** [CloudCannon/aviator-jekyll-template#10]
I had some longer APIs that didn't fit in the default 210px wide navigation area. I enlarged the area by changing $nav-width in style.css.

This caused a small gap.
![gap](https://user-images.githubusercontent.com/8692463/32404371-18ea15d6-c157-11e7-8516-6362b222f28e.png)

I fixed it by changing the margin from 210px to read the value from the variable in _main.scss
.main {
	margin: 0 0 0 $nav-width;

**Comment by mneumegen** [comment]
Good idea. Fixed on master.
