### ISSUE TITLE
Invalid links on demo page

### ISSUE THREAD

**Issue by Xeverous** [CloudCannon/aviator-jekyll-template#11]
Links to 1st, 2nd, 3rd and 4th layout on demo page are invalid

The links are:

    https://jekyll-demos.github.io/index.html
    https://jekyll-demos.github.io/index2.html
    https://jekyll-demos.github.io/index3.html
    https://jekyll-demos.github.io/index4.html
    
While they should be:

    https://jekyll-demos.github.io/Aviator-Jekyll-Theme/index.html
    https://jekyll-demos.github.io/Aviator-Jekyll-Theme/index2.html
    https://jekyll-demos.github.io/Aviator-Jekyll-Theme/index3.html
    https://jekyll-demos.github.io/Aviator-Jekyll-Theme/index4.html

**Comment by mneumegen** [comment]
Unfortunately we don't manage this domain and they seem to be using an old version of the template.
