### ISSUE TITLE
Not very customizable

### ISSUE THREAD

**Issue by DerKnerd** [CloudCannon/aviator-jekyll-template#13]
Hi CloudCannon-Team,

I came across this jekyll theme and I was really impressed by the looks. But sadly the scss code itself wasn't that pretty or easy customizable. Would you mind making it easier customizable and maybe add autoprefixer? It would really increase the quality of this theme. If you need assistance with the doing, just ask me :slightly_smiling_face: 

Greetings
Knerd

**Comment by bglw** [comment]
👋 Apologies for this issue being lost — we do have a [range of new templates now](https://cloudcannon.com/community/themes/) that may be more customizable for your needs.
