### ISSUE TITLE
Change url structure

### ISSUE THREAD

**Issue by mustela** [CloudCannon/aviator-jekyll-template#14]
Hello there! 

It may be a silly question, but I can't seem to be find a way to change the urls from `/#documentationgetting_started` to `/documentations/getting-started`. 

I've try setting global definitions like `permalink: /:categories/:year/:month/:day/:title/:output_ext` or per collection, per page, but nothing seems to be working. 

Any way to change that? 

Thanks!

**Comment by bglw** [comment]
👋 Apologies for this issue being lost — we do have a [range of new templates now](https://cloudcannon.com/community/themes/) that may be more customizable for your needs.
