### ISSUE TITLE
Highlighter?

### ISSUE THREAD

**Issue by ImReallyShiny** [CloudCannon/aviator-jekyll-template#4]
Which languages are supported with the Highlighter? And where do we set which type of Highlighter we use? (I want to highlight C++ and C code but doing ~~~ c++ doesnt work)

**Comment by mneumegen** [comment]
Hi @ImReallyShiny,

It uses the default Jekyll syntax highlighter - [Rouge](http://rouge.jneen.net/). I haven't tried this but if you use cpp it might work.
